import { Matter, DailyTask } from '@/types';

export const INITIAL_MATTERS: Matter[] = [
  {
    id: 'mla-m-001',
    date: '2026-09-08',
    priority: 'High',
    status: 'Ongoing',
    practiceArea: 'Corporate',
    matterTitle: 'Legal Due Diligence & Share Transfer for Foreign Investor Acquisition',
    clientReference: 'Client · MLA/CORP/042/2026',
    supervisingLawyer: 'Mehrteab Leul (Managing Partner)',
    deadline: '2026-09-18',
    timeSpentHours: 18.5,
    activitiesDone: 'Reviewed Memorandum and Articles of Association under the 2021 Commercial Code; drafted red-flag legal due diligence report focusing on share valuation and pre-emptive rights.',
    skillsLawsInvolved: 'Commercial Code Procl. No. 1243/2021; Investment Procl. No. 1180/2020; Ministry of Trade & Regional Integration (MoTRI) filing directives.',
    lessonsLearned: 'Under the 2021 Commercial Code, pre-emptive rights of existing shareholders in a private limited company (PLC) cannot be waived implicitly; written waiver or minute notarization is strictly scrutinized by MoTRI during registration.',
    followUpSteps: 'Schedule alignment call with buyer legal counsel; draft revised Share Purchase Agreement (SPA) closing conditions.',
    subtasks: [
      { id: 'st-001-1', title: 'Finalize Red-Flag Due Diligence Matrix', completed: true, dueDate: '2026-09-10', priority: 'High' },
      { id: 'st-001-2', title: 'Prepare Board Resolution for Share Transfer Approval', completed: false, dueDate: '2026-09-15', priority: 'High' },
      { id: 'st-001-3', title: 'Confirm MoTRI Document Authentication Requirements', completed: false, dueDate: '2026-09-18', priority: 'Medium' },
    ],
    confidenceRating: 4,
    createdAt: '2026-09-01T09:00:00Z',
    updatedAt: '2026-09-11T16:20:00Z',
  },
  {
    id: 'mla-m-002',
    date: '2026-09-05',
    priority: 'High',
    status: 'Ongoing',
    practiceArea: 'Tax',
    matterTitle: 'Transfer Pricing Assessment Appeal & Withholding Tax Advisory',
    clientReference: 'Client · MLA/TAX/019/2026',
    supervisingLawyer: 'Senior Associate (Tax & Regulatory)',
    deadline: '2026-09-14',
    timeSpentHours: 14.0,
    activitiesDone: 'Analyzed Ministry of Revenues (MoR) reassessment notice alleging non-arm’s length management fees; drafted preliminary appeal petition citing OECD transfer pricing guidelines applicable under Ethiopian law.',
    skillsLawsInvolved: 'Federal Income Tax Proclamation No. 979/2016; Tax Administration Proclamation No. 983/2016; Transfer Pricing Directive No. 43/2015.',
    lessonsLearned: 'When submitting objections to the Tax Assessment Review Committee under Art. 55 of Proclamation 983/2016, strict adherence to the 30-day filing window from receipt of assessment is jurisdictional; failure to pay the 25% disputed tax deposit invalidates the appeal hearing.',
    followUpSteps: 'File formal objection petition with MoR Tax Decisions Review Committee before deadline.',
    subtasks: [
      { id: 'st-002-1', title: 'Assemble benchmark comparability study for management fees', completed: true, dueDate: '2026-09-07', priority: 'High' },
      { id: 'st-002-2', title: 'Finalize 30-day appeal petition to MoR Committee', completed: false, dueDate: '2026-09-14', priority: 'High' },
      { id: 'st-002-3', title: 'Verify client proof of 25% tax deposit payment', completed: false, dueDate: '2026-09-13', priority: 'High' },
    ],
    confidenceRating: 4,
    createdAt: '2026-09-02T10:30:00Z',
    updatedAt: '2026-09-10T14:15:00Z',
  },
  {
    id: 'mla-m-003',
    date: '2026-08-28',
    priority: 'Medium',
    status: 'Completed',
    practiceArea: 'Employment & Immigration',
    matterTitle: 'Collective Redundancy Procedure & Expatriate Work Permit Audit',
    clientReference: 'Client · MLA/EMP/058/2026',
    supervisingLawyer: 'Getu Shiferaw (Partner)',
    deadline: '2026-09-02',
    timeSpentHours: 12.5,
    activitiesDone: 'Drafted notification letters to Ministry of Labour and Skills (MoLS) regarding workforce restructuring; prepared redundancy compensation schedule and advised on severance calculation under Proclamation 1156/2019.',
    skillsLawsInvolved: 'Labour Proclamation No. 1156/2019 (Articles 28-30); Immigration Proclamation; MoLS Expatriate Quota Directives.',
    lessonsLearned: 'Article 29 reduction of workforce mandates a 30-day prior written notice to the Ministry with trade union/workers representative consultation. Failing to document notice creates exposure to wrongful termination claims and mandatory reinstatement orders.',
    followUpSteps: 'Obtain MoLS stamped receipt copies for client records archive.',
    subtasks: [
      { id: 'st-003-1', title: 'Review severance breakdown table for 24 affected employees', completed: true, dueDate: '2026-08-30', priority: 'Medium' },
      { id: 'st-003-2', title: 'Submit notification package to MoLS Sub-city branch', completed: true, dueDate: '2026-09-02', priority: 'High' },
    ],
    confidenceRating: 5,
    createdAt: '2026-08-25T11:00:00Z',
    updatedAt: '2026-09-02T17:00:00Z',
  },
  {
    id: 'mla-m-004',
    date: '2026-09-02',
    priority: 'High',
    status: 'Ongoing',
    practiceArea: 'Litigation & Arbitration',
    matterTitle: 'Commercial Arbitration Statement of Defense before AACCSA Tribunal',
    clientReference: 'Client · MLA/LIT/011/2026',
    supervisingLawyer: 'Senior Associate (Litigation & Arbitration)',
    deadline: '2026-09-22',
    timeSpentHours: 21.0,
    activitiesDone: 'Reviewed construction claim notice under FIDIC Silver Book; drafted jurisdictional objection challenging arbitration tribunal authority under Arbitration Proclamation 1237/2021; gathered witness statement outlines.',
    skillsLawsInvolved: 'Arbitration and Conciliation Proclamation No. 1237/2021; Addis Ababa Chamber of Commerce Arbitration Rules (2022); Civil Procedure Code.',
    lessonsLearned: 'Under Proclamation 1237/2021 Art. 19 (competence-competence), jurisdictional challenges must be raised before or at the time of submitting the statement of defense, otherwise waived.',
    followUpSteps: 'Coordinate expert engineering report on delayed site handover; finalize preliminary objections filing.',
    subtasks: [
      { id: 'st-004-1', title: 'Draft Statement of Defense & Counterclaim', completed: false, dueDate: '2026-09-18', priority: 'High' },
      { id: 'st-004-2', title: 'Compile documentary exhibits bundle (Vols I & II)', completed: false, dueDate: '2026-09-20', priority: 'Medium' },
      { id: 'st-004-3', title: 'Conduct prep session with key site project manager', completed: true, dueDate: '2026-09-06', priority: 'High' },
    ],
    confidenceRating: 3,
    createdAt: '2026-08-30T08:30:00Z',
    updatedAt: '2026-09-11T18:00:00Z',
  },
  {
    id: 'mla-m-005',
    date: '2026-09-07',
    priority: 'Medium',
    status: 'Ongoing',
    practiceArea: 'Finance & Projects',
    matterTitle: 'Collateral Registration under Movable Property Security Right & Loan Facility',
    clientReference: 'Client · MLA/FIN/033/2026',
    supervisingLawyer: 'Senior Partner (Corporate & Finance)',
    deadline: '2026-09-17',
    timeSpentHours: 9.5,
    activitiesDone: 'Drafted security agreement covering industrial equipment & receivables; registered electronic notice on the National Bank of Ethiopia Collateral Registry System (CRSO).',
    skillsLawsInvolved: 'Movable Property Security Right Proclamation No. 1147/2019; NBE Directives on External Loan Registration.',
    lessonsLearned: 'Priority of movable collateral is strictly determined by time of registration on the CRSO electronic registry, not date of contract execution. Early registration prior to fund disbursement is crucial.',
    followUpSteps: 'Secure NBE external debt registration certificate for foreign lender currency convertibility.',
    subtasks: [
      { id: 'st-005-1', title: 'Generate CRSO search verification certificate', completed: true, dueDate: '2026-09-08', priority: 'High' },
      { id: 'st-005-2', title: 'Draft legal opinion letter on enforceability of pledge', completed: false, dueDate: '2026-09-17', priority: 'High' },
    ],
    confidenceRating: 4,
    createdAt: '2026-09-05T14:00:00Z',
    updatedAt: '2026-09-11T12:00:00Z',
  },
  {
    id: 'mla-m-006',
    date: '2026-08-20',
    priority: 'Low',
    status: 'Completed',
    practiceArea: 'IP & Technology',
    matterTitle: 'Trademark Opposition Proceeding & Madrid Protocol Filing at EIPO',
    clientReference: 'Client · MLA/IP/024/2026',
    supervisingLawyer: 'Special Legal Counsel',
    deadline: '2026-08-31',
    timeSpentHours: 8.0,
    activitiesDone: 'Drafted opposition memorandum against confusingly similar mark published in Official Trademark Gazette; lodged formal objection before Ethiopian Intellectual Property Authority (EIPA).',
    skillsLawsInvolved: 'Trademark Registration and Protection Proclamation No. 501/2006; Trademark Regulations No. 273/2012.',
    lessonsLearned: 'Opposition period under Proclamation 501/2006 is strictly 60 days from publication date without possibility of discretionary extension by the registrar. Monitoring gazettes on the first week of publication is vital.',
    followUpSteps: 'Await EIPA registrar hearing notice.',
    subtasks: [
      { id: 'st-006-1', title: 'Collect certified extract of prior registered marks', completed: true, dueDate: '2026-08-24', priority: 'Medium' },
      { id: 'st-006-2', title: 'File opposition brief and pay official fee at EIPA', completed: true, dueDate: '2026-08-31', priority: 'High' },
    ],
    confidenceRating: 5,
    createdAt: '2026-08-18T10:00:00Z',
    updatedAt: '2026-08-31T15:30:00Z',
  },
  {
    id: 'mla-m-007',
    date: '2026-09-04',
    priority: 'High',
    status: 'Pending',
    practiceArea: 'Mining, Energy & Real Estate',
    matterTitle: 'Mining Exploration License Compliance Review & Environmental ESG Advisory',
    clientReference: 'Client · MLA/MIN/007/2026',
    supervisingLawyer: 'Mehrteab Leul (Managing Partner)',
    deadline: '2026-09-25',
    timeSpentHours: 11.0,
    activitiesDone: 'Reviewed exploration license conditions; verified community development agreement (CDA) compliance and annual work program spend obligations with Ministry of Mines.',
    skillsLawsInvolved: 'Mining Operations Proclamation No. 678/2010 (as amended by Procl. 816/2013); Environmental Impact Assessment Proclamation No. 299/2002.',
    lessonsLearned: 'Failure to spend at least 85% of proposed exploration expenditure without prior Ministry approval can trigger revocation notices. Always cross-examine financial audit reports against approved program budgets before ministerial submissions.',
    followUpSteps: 'Prepare response memorandum to Ministry of Mines audit inquiry.',
    subtasks: [
      { id: 'st-007-1', title: 'Reconcile 2025 audited accounts with approved work plan', completed: true, dueDate: '2026-09-06', priority: 'High' },
      { id: 'st-007-2', title: 'Draft formal explanation letter to Licensing Directorate', completed: false, dueDate: '2026-09-22', priority: 'High' },
    ],
    confidenceRating: 4,
    createdAt: '2026-09-03T09:00:00Z',
    updatedAt: '2026-09-10T11:00:00Z',
  },
  {
    id: 'mla-m-008',
    date: '2026-08-15',
    priority: 'Medium',
    status: 'Completed',
    practiceArea: 'NGO & Civil Society',
    matterTitle: 'CSO By-Laws Amendment & Operational Agreement with ACSO',
    clientReference: 'Client · MLA/NGO/015/2026',
    supervisingLawyer: 'Getu Shiferaw (Partner)',
    deadline: '2026-08-27',
    timeSpentHours: 7.5,
    activitiesDone: 'Drafted revised organizational by-laws for international NGO country office; advised on administrative expenditure ceiling compliance (20/80 rule) under Civil Society Proclamation.',
    skillsLawsInvolved: 'Civil Society Organizations Proclamation No. 1113/2019; ACSO Directive No. 848/2021 on Administrative and Operational Expenses.',
    lessonsLearned: 'Proclamation 1113/2019 allows foreign CSOs to engage in advocacy and human rights, unlike repealed Procl. 621/2009. However, administrative overhead calculation remains strictly audited by ACSO.',
    followUpSteps: 'File final registered constitution in client vault.',
    subtasks: [
      { id: 'st-008-1', title: 'Prepare general assembly minutes for by-laws update', completed: true, dueDate: '2026-08-20', priority: 'Medium' },
      { id: 'st-008-2', title: 'Obtain ACSO stamped registration certificate', completed: true, dueDate: '2026-08-27', priority: 'High' },
    ],
    confidenceRating: 5,
    createdAt: '2026-08-12T13:00:00Z',
    updatedAt: '2026-08-27T16:00:00Z',
  },
];

export const INITIAL_TASKS: DailyTask[] = [
  {
    id: 'task-standalone-1',
    title: 'Review Federal Supreme Court Cassation Bench Bulletin Vol. 28 for tax precedent',
    priority: 'High',
    dueDate: '2026-09-14',
    completed: false,
    isMatterSubtask: false,
    createdAt: '2026-09-10T08:00:00Z',
  },
  {
    id: 'task-standalone-2',
    title: 'Update MLA internal regulatory tracker on foreign exchange liberalisation directives',
    priority: 'Medium',
    dueDate: '2026-09-16',
    completed: false,
    isMatterSubtask: false,
    createdAt: '2026-09-11T09:30:00Z',
  },
  {
    id: 'task-standalone-3',
    title: 'Submit monthly billable hours log and CLE attendance credits to HR',
    priority: 'Low',
    dueDate: '2026-09-18',
    completed: true,
    isMatterSubtask: false,
    createdAt: '2026-09-08T10:00:00Z',
  },
  // Auto-linked matter subtasks:
  {
    id: 'task-linked-st-001-2',
    title: 'Prepare Board Resolution for Share Transfer Approval',
    priority: 'High',
    dueDate: '2026-09-15',
    completed: false,
    isMatterSubtask: true,
    matterId: 'mla-m-001',
    matterTitle: 'Legal Due Diligence & Share Transfer for Foreign Investor Acquisition',
    clientReference: 'Client · MLA/CORP/042/2026',
    subtaskId: 'st-001-2',
    createdAt: '2026-09-01T09:00:00Z',
  },
  {
    id: 'task-linked-st-001-3',
    title: 'Confirm MoTRI Document Authentication Requirements',
    priority: 'Medium',
    dueDate: '2026-09-18',
    completed: false,
    isMatterSubtask: true,
    matterId: 'mla-m-001',
    matterTitle: 'Legal Due Diligence & Share Transfer for Foreign Investor Acquisition',
    clientReference: 'Client · MLA/CORP/042/2026',
    subtaskId: 'st-001-3',
    createdAt: '2026-09-01T09:00:00Z',
  },
  {
    id: 'task-linked-st-002-2',
    title: 'Finalize 30-day appeal petition to MoR Committee',
    priority: 'High',
    dueDate: '2026-09-14',
    completed: false,
    isMatterSubtask: true,
    matterId: 'mla-m-002',
    matterTitle: 'Transfer Pricing Assessment Appeal & Withholding Tax Advisory',
    clientReference: 'Client · MLA/TAX/019/2026',
    subtaskId: 'st-002-2',
    createdAt: '2026-09-02T10:30:00Z',
  },
  {
    id: 'task-linked-st-002-3',
    title: 'Verify client proof of 25% tax deposit payment',
    priority: 'High',
    dueDate: '2026-09-13',
    completed: false,
    isMatterSubtask: true,
    matterId: 'mla-m-002',
    matterTitle: 'Transfer Pricing Assessment Appeal & Withholding Tax Advisory',
    clientReference: 'Client · MLA/TAX/019/2026',
    subtaskId: 'st-002-3',
    createdAt: '2026-09-02T10:30:00Z',
  },
  {
    id: 'task-linked-st-004-1',
    title: 'Draft Statement of Defense & Counterclaim',
    priority: 'High',
    dueDate: '2026-09-18',
    completed: false,
    isMatterSubtask: true,
    matterId: 'mla-m-004',
    matterTitle: 'Commercial Arbitration Statement of Defense before AACCSA Tribunal',
    clientReference: 'Client · MLA/LIT/011/2026',
    subtaskId: 'st-004-1',
    createdAt: '2026-08-30T08:30:00Z',
  },
  {
    id: 'task-linked-st-004-2',
    title: 'Compile documentary exhibits bundle (Vols I & II)',
    priority: 'Medium',
    dueDate: '2026-09-20',
    completed: false,
    isMatterSubtask: true,
    matterId: 'mla-m-004',
    matterTitle: 'Commercial Arbitration Statement of Defense before AACCSA Tribunal',
    clientReference: 'Client · MLA/LIT/011/2026',
    subtaskId: 'st-004-2',
    createdAt: '2026-08-30T08:30:00Z',
  },
  {
    id: 'task-linked-st-005-2',
    title: 'Draft legal opinion letter on enforceability of pledge',
    priority: 'High',
    dueDate: '2026-09-17',
    completed: false,
    isMatterSubtask: true,
    matterId: 'mla-m-005',
    matterTitle: 'Collateral Registration under Movable Property Security Right & Loan Facility',
    clientReference: 'Client · MLA/FIN/033/2026',
    subtaskId: 'st-005-2',
    createdAt: '2026-09-05T14:00:00Z',
  },
  {
    id: 'task-linked-st-007-2',
    title: 'Draft formal explanation letter to Licensing Directorate',
    priority: 'High',
    dueDate: '2026-09-22',
    completed: false,
    isMatterSubtask: true,
    matterId: 'mla-m-007',
    matterTitle: 'Mining Exploration License Compliance Review & Environmental ESG Advisory',
    clientReference: 'Client · MLA/MIN/007/2026',
    subtaskId: 'st-007-2',
    createdAt: '2026-09-03T09:00:00Z',
  },
];
